name: Primeiro Workflow
on: workflow_dispatch
jobs:
  primeiro-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "Hello world"
      - name: Print goodbye
        run: echo "Rala pivete!"
